[package]
edition.workspace = true
license-file.workspace = true
name = "types-test"
repository.workspace = true
version.workspace = true

[package.metadata.release]
pre-release-replacements = [
    { file = "Scarb.lock", search = "^name = \"dojo\"\nversion = \".*\"$", replace = "name = \"dojo\"\nversion = \"{{version}}\"", min = 1 },
    { file = "Scarb.toml", search = "^version = \".*\"$", replace = "version = \"{{version}}\"", min = 1 },
]

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
scarb-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
dojo-test-utils = { path = "../../dojo-test-utils", features = [ "build-examples" ] }
dojo-world = { path = "../../dojo-world" }
torii-core = { path = "../core" }
scarb.workspace = true
serial_test = "2.0.0"
sozo = { path = "../../sozo" }
starknet-crypto.workspace = true
starknet.workspace = true
tokio-stream = "0.1.11"
tokio-util = "0.7.7"
tokio.workspace = true
